server:
  port: 8888 # 服务端口

spring:
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M
  profiles:
    active: dev # 环境设置
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/round_tea_table?serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    过滤null字段
    default-property-inclusion: non_null


  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: 123456 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/fg/roundteatable/mapper/xml/*.xml


mybatis-plus:
  #mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 在classpath前添加星号可以使项目热加载成功
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fg.roundteatable
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
# 设置日志级别
#logging:
#  level:
#    root: INFO

aliyun:
  sts:
    endpoint: sts.cn-hangzhou.aliyuncs.com
    ki: LTAI5t6QoGkprnCHxVprT6j2
    ks: q7qQ9W7WDg0mfHR4IrtdIqgcuqbdHt
    #bucket可以在控制台创建，也可以使用java代码创建
    bucketname: roundteatable-file-buckets
    roleArn: acs:ram::1961627345815863:role/ramosstest
  vod:
    ki: LTAI5tFeHEvGrfLwpA2hJxhX
    ks: pD0nHpS9js7AZNGwhiUrh1VLU6BF3U
    templateGroupId: 5969d075d72bebf65b39670f019ed6ed #转码模板组id
    workflowId: b2cde7eaf99a895b89ab1a88abee0a25 #工作流id